services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: redisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"