spring.application.name=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/redisdb
spring.datasource.username=postgres
spring.datasource.password=2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true